# Importamos desde la subcarpeta nodes
from .nodes.resource_link_hub import NODE_CLASS_MAPPINGS as LINK_HUB_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LINK_HUB_NAMES
from .nodes.hardware_monitor_studio import NODE_CLASS_MAPPINGS as HW_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as HW_NAMES
from .nodes.benchmark_timer_studio import NODE_CLASS_MAPPINGS as TIMER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TIMER_NAMES
from .nodes.minimax_model_loader import NODE_CLASS_MAPPINGS as MINIMAX_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MINIMAX_NAMES
from .nodes.mcvalley_minimax_i2v import NODE_CLASS_MAPPINGS as FAST_I2V_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FAST_I2V_NAMES
from .nodes.minimax_direct_lora import NODE_CLASS_MAPPINGS as DIRECT_LORA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DIRECT_LORA_NAMES
from .nodes.prompt_translator_local import NODE_CLASS_MAPPINGS as LOCAL_TRANS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOCAL_TRANS_NAMES
from .nodes.video_prompt_director import NODE_CLASS_MAPPINGS as DIRECTOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DIRECTOR_NAMES
from .nodes.minimax_latent_upscaler_studio import NODE_CLASS_MAPPINGS as LATENT_STUDIO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LATENT_STUDIO_NAMES
from .nodes.frame_inspector_trimmer import NODE_CLASS_MAPPINGS as INSPECT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as INSPECT_NAMES
from .nodes.amd_ai_upscaler_refiner import NODE_CLASS_MAPPINGS as AMD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AMD_DISPLAY_MAPPINGS
from .nodes.minimax_video_time_director import NODE_CLASS_MAPPINGS as TIME_DIR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TIME_DIR_NAMES
from .nodes.empty_latent_div32 import NODE_CLASS_MAPPINGS as EMPTY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EMPTY_NAMES
from .nodes.prompt_layer_stacker import NODE_CLASS_MAPPINGS as STACKER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STACKER_NAMES

NODE_CLASS_MAPPINGS = {
    **LINK_HUB_MAPPINGS,
    **HW_MAPPINGS,
    **TIMER_MAPPINGS,
    **MINIMAX_MAPPINGS,
    **FAST_I2V_MAPPINGS,
    **DIRECT_LORA_MAPPINGS,
    **LOCAL_TRANS_MAPPINGS,
    **DIRECTOR_MAPPINGS,
    **LATENT_STUDIO_MAPPINGS,
    **INSPECT_MAPPINGS,
    **AMD_MAPPINGS,
    **TIME_DIR_MAPPINGS,
    **EMPTY_MAPPINGS,
    **STACKER_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LINK_HUB_NAMES,
    **HW_NAMES,
    **TIMER_NAMES,
    **MINIMAX_NAMES,
    **FAST_I2V_NAMES,
    **DIRECT_LORA_NAMES,
    **LOCAL_TRANS_NAMES,
    **DIRECTOR_NAMES,
    **LATENT_STUDIO_NAMES,
    **INSPECT_NAMES,
    **AMD_DISPLAY_MAPPINGS,
    **TIME_DIR_NAMES,
    **EMPTY_NAMES,
    **STACKER_NAMES,
}

# La carpeta web sigue en la raíz
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
